import { useMemo, useState } from 'react'
import { toast } from 'sonner'
import { BadgePercent, CheckCircle2, Landmark, RefreshCw, Wallet } from 'lucide-react'
import { useApp } from '@/lib/store'
import { useL } from '@/lib/i18n'
import { useData } from '@/lib/data'
import { ars, dateTime, pct } from '@/lib/format'
import { cn } from '@/lib/utils'
import type { EstadoPago } from '@/data/types'
import { Button, Card, Kpi, PageHeader, Tabs, Td, Th } from '@/components/ui'
import { DEV, DevNotice, PreviewBanner } from '@/components/notices'
import { PagoBadge, useKicker } from '@/components/page'

export default function Cobros() {
  const lang = useApp((s) => s.lang)
  const L = useL()
  const { kicker, tone } = useKicker()
  const txs = useData((s) => s.transacciones)
  const retry = useData((s) => s.retryTx)
  const [f, setF] = useState<'todos' | EstadoPago>('todos')

  const today = new Date()
  today.setHours(0, 0, 0, 0)
  const hoy = txs.filter((t) => t.fecha >= +today)
  const aprob = hoy.filter((t) => t.estado === 'aprobado')
  const cobrado = aprob.reduce((s, t) => s + t.monto, 0)
  const comis = aprob.reduce((s, t) => s + t.comision, 0)
  const tasa = hoy.length ? (aprob.length / hoy.filter((t) => t.estado !== 'pendiente').length) * 100 : 0
  const list = useMemo(() => txs.filter((t) => f === 'todos' || t.estado === f), [txs, f])
  const count = (e: EstadoPago) => txs.filter((t) => t.estado === e).length

  return (
    <div>
      <PreviewBanner
        id="cobros"
        bullets={[
          ['Link de pago único por pedido, generado por la IA en el chat.', 'A unique payment link per order, generated by the AI in the chat.'],
          ['Confirmación automática del pago por webhook: sin mirar el celular.', 'Automatic payment confirmation via webhook: no need to check your phone.'],
          ['Comisión y neto calculados solos, con reintentos de pagos rechazados.', 'Fee and net amount calculated automatically, with retries for rejected payments.'],
        ]}
      />
      <PageHeader kicker={kicker} kickerTone={tone} title={L('Cobros · Mercado Pago', 'Payments · Mercado Pago')} subtitle={L('Transacciones de hoy y ayer', "Today's and yesterday's transactions")} />
      <DevNotice {...DEV.mp} />
      <div className="mb-5 grid grid-cols-2 gap-3 lg:grid-cols-4">
        <Kpi label={L('Cobrado hoy', 'Collected today')} value={ars(cobrado, lang)} icon={Wallet} delta={11} />
        <Kpi label={L('Comisiones', 'Fees')} value={ars(comis, lang)} icon={BadgePercent} accent="amber" hint={pct(6.29, lang, 2)} />
        <Kpi label={L('Neto a liquidar', 'Net to settle')} value={ars(cobrado - comis, lang)} icon={Landmark} accent="blue" />
        <Kpi label={L('Tasa de aprobación', 'Approval rate')} value={pct(tasa, lang, 1)} icon={CheckCircle2} accent="orange" />
      </div>
      <Tabs
        className="mb-4 w-fit"
        value={f}
        onChange={setF}
        items={[
          { value: 'todos', label: L('Todas', 'All'), count: txs.length },
          { value: 'aprobado', label: L('Aprobadas', 'Approved'), count: count('aprobado') },
          { value: 'rechazado', label: L('Rechazadas', 'Rejected'), count: count('rechazado') },
          { value: 'pendiente', label: L('Pendientes', 'Pending'), count: count('pendiente') },
          { value: 'reembolsado', label: L('Reembolsadas', 'Refunded'), count: count('reembolsado') },
        ]}
      />
      <Card className="overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="border-b border-line bg-surface2/60">
              <tr>
                <Th>ID</Th>
                <Th>{L('Pedido', 'Order')}</Th>
                <Th className="text-right">{L('Monto', 'Amount')}</Th>
                <Th className="hidden text-right md:table-cell">{L('Comisión', 'Fee')}</Th>
                <Th className="hidden text-right md:table-cell">{L('Neto', 'Net')}</Th>
                <Th>{L('Estado', 'Status')}</Th>
                <Th className="hidden lg:table-cell">{L('Hora', 'Time')}</Th>
                <Th />
              </tr>
            </thead>
            <tbody className="divide-y divide-line">
              {list.map((t) => (
                <tr key={t.id} className={cn('hover:bg-surface2/50', t.estado === 'rechazado' && 'bg-danger-soft/25')}>
                  <Td className="num text-muted">{t.id}</Td>
                  <Td className="num">#{t.pedidoCodigo}</Td>
                  <Td className="num text-right font-medium">{ars(t.monto, lang)}</Td>
                  <Td className="num hidden text-right text-muted md:table-cell">−{ars(t.comision, lang)}</Td>
                  <Td className="num hidden text-right md:table-cell">{ars(t.neto, lang)}</Td>
                  <Td>
                    <div className="flex flex-col items-start gap-0.5">
                      <PagoBadge estado={t.estado} />
                      {t.nota && <span className="max-w-[220px] whitespace-normal text-[11.5px] text-muted">{L(t.nota.es, t.nota.en)}</span>}
                    </div>
                  </Td>
                  <Td className="hidden text-muted lg:table-cell">{dateTime(t.fecha, lang)}</Td>
                  <Td className="text-right">
                    {t.estado === 'rechazado' && (
                      <Button
                        size="sm"
                        variant="secondary"
                        onClick={() => {
                          retry(t.id)
                          toast.success(L(`Reintento de ${t.id} aprobado`, `Retry of ${t.id} approved`))
                        }}
                      >
                        <RefreshCw size={13} /> {L('Reintentar', 'Retry')}
                      </Button>
                    )}
                  </Td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  )
}
